//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostureRepo.Repository_and_BO.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short Sets { get; set; }
        public short Reps { get; set; }
        public int ExerciseTemplateId { get; set; }
        public int WorkoutId { get; set; }
        public short SortOrder { get; set; }
    
        public virtual ExerciseTemplate ExerciseTemplate { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
